name: Update Documentation

on:
  issues:
    types: [closed]
  workflow_dispatch:
    inputs:
      task_id:
        description: 'Task ID (e.g., 1, 2, 3)'
        required: false
        type: string
      task_title:
        description: 'Task title'
        required: false
        type: string
      completion_notes:
        description: 'Completion notes'
        required: false
        type: string

jobs:
  update-docs:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub
    
    - name: Update documentation
      run: |
        python update_docs.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/wiki/
        git diff --staged --quiet || git commit -m "docs: Update documentation after task completion"
        git push
